//! Command & Conquer: Generals (base) faction rosters — USA / China / GLA.
//! Buildings and ground units modelled after the original tech trees.

use super::match_sim::{BuildDef, UnitDef};

#[inline]
pub fn faction_ok(allowed: &str, faction: &str) -> bool {
    allowed == "any" || allowed == faction
}

pub fn buildables() -> &'static [BuildDef] {
    &[
        // ——— Shared / HQ is spawned separately ———
        // ——— USA ———
        BuildDef {
            kind: "power_plant",
            name: "Cold Fusion Reactor",
            faction: "usa",
            cost_gold: 1_000,
            build_ms: 8_000,
            power: 100,
            hp: 1_800.0,
        },
        BuildDef {
            kind: "barracks",
            name: "Barracks",
            faction: "usa",
            cost_gold: 800,
            build_ms: 10_000,
            power: -20,
            hp: 2_200.0,
        },
        BuildDef {
            kind: "supply",
            name: "Supply Center",
            faction: "usa",
            cost_gold: 500,
            build_ms: 7_000,
            power: -10,
            hp: 1_500.0,
        },
        BuildDef {
            kind: "war_factory",
            name: "War Factory",
            faction: "usa",
            cost_gold: 2_800,
            build_ms: 14_000,
            power: -30,
            hp: 2_800.0,
        },
        BuildDef {
            kind: "airfield",
            name: "Airfield",
            faction: "usa",
            cost_gold: 1_500,
            build_ms: 12_000,
            power: -25,
            hp: 2_400.0,
        },
        BuildDef {
            kind: "strategy_center",
            name: "Strategy Center",
            faction: "usa",
            cost_gold: 3_500,
            build_ms: 18_000,
            power: -40,
            hp: 3_200.0,
        },
        BuildDef {
            kind: "turret",
            name: "Patriot Battery",
            faction: "usa",
            cost_gold: 1_650,
            build_ms: 11_000,
            power: -25,
            hp: 2_600.0,
        },
        BuildDef {
            kind: "firebase",
            name: "Fire Base",
            faction: "usa",
            cost_gold: 1_500,
            build_ms: 12_000,
            power: -20,
            hp: 3_500.0,
        },
        BuildDef {
            kind: "particle_cannon",
            name: "Particle Cannon",
            faction: "usa",
            cost_gold: 8_000,
            build_ms: 45_000,
            power: -80,
            hp: 4_000.0,
        },
        BuildDef {
            kind: "radar",
            name: "Radar Dome",
            faction: "usa",
            cost_gold: 1_700,
            build_ms: 16_000,
            power: -40,
            hp: 1_400.0,
        },
        // ——— China ———
        BuildDef {
            kind: "nuclear_reactor",
            name: "Nuclear Reactor",
            faction: "china",
            cost_gold: 1_050,
            build_ms: 9_000,
            power: 120,
            hp: 2_000.0,
        },
        BuildDef {
            kind: "barracks",
            name: "Barracks",
            faction: "china",
            cost_gold: 650,
            build_ms: 9_000,
            power: -15,
            hp: 2_400.0,
        },
        BuildDef {
            kind: "supply",
            name: "Supply Center",
            faction: "china",
            cost_gold: 500,
            build_ms: 7_000,
            power: -10,
            hp: 1_600.0,
        },
        BuildDef {
            kind: "war_factory",
            name: "War Factory",
            faction: "china",
            cost_gold: 2_700,
            build_ms: 14_000,
            power: -30,
            hp: 3_000.0,
        },
        BuildDef {
            kind: "airfield",
            name: "Airfield",
            faction: "china",
            cost_gold: 1_500,
            build_ms: 12_000,
            power: -25,
            hp: 2_400.0,
        },
        BuildDef {
            kind: "propaganda_center",
            name: "Propaganda Center",
            faction: "china",
            cost_gold: 2_800,
            build_ms: 16_000,
            power: -35,
            hp: 2_800.0,
        },
        BuildDef {
            kind: "internet_center",
            name: "Internet Center",
            faction: "china",
            cost_gold: 3_400,
            build_ms: 18_000,
            power: -30,
            hp: 2_200.0,
        },
        BuildDef {
            kind: "bunker",
            name: "Bunker",
            faction: "china",
            cost_gold: 750,
            build_ms: 8_000,
            power: -10,
            hp: 4_000.0,
        },
        BuildDef {
            kind: "gatling_cannon",
            name: "Gattling Cannon",
            faction: "china",
            cost_gold: 1_800,
            build_ms: 12_000,
            power: -30,
            hp: 2_200.0,
        },
        BuildDef {
            kind: "nuclear_silo",
            name: "Nuclear Missile Silo",
            faction: "china",
            cost_gold: 8_500,
            build_ms: 50_000,
            power: -100,
            hp: 4_500.0,
        },
        BuildDef {
            kind: "radar",
            name: "Listening Post",
            faction: "china",
            cost_gold: 1_400,
            build_ms: 14_000,
            power: -25,
            hp: 1_200.0,
        },
        // ——— GLA (no power grid) ———
        BuildDef {
            kind: "barracks",
            name: "Barracks",
            faction: "gla",
            cost_gold: 500,
            build_ms: 8_000,
            power: 0,
            hp: 1_800.0,
        },
        BuildDef {
            kind: "supply_stash",
            name: "Supply Stash",
            faction: "gla",
            cost_gold: 500,
            build_ms: 6_000,
            power: 0,
            hp: 1_200.0,
        },
        BuildDef {
            kind: "arms_dealer",
            name: "Arms Dealer",
            faction: "gla",
            cost_gold: 2_000,
            build_ms: 12_000,
            power: 0,
            hp: 2_400.0,
        },
        BuildDef {
            kind: "palace",
            name: "Palace",
            faction: "gla",
            cost_gold: 3_500,
            build_ms: 20_000,
            power: 0,
            hp: 3_500.0,
        },
        BuildDef {
            kind: "black_market",
            name: "Black Market",
            faction: "gla",
            cost_gold: 2_700,
            build_ms: 15_000,
            power: 0,
            hp: 2_000.0,
        },
        BuildDef {
            kind: "stinger_site",
            name: "Stinger Site",
            faction: "gla",
            cost_gold: 1_450,
            build_ms: 10_000,
            power: 0,
            hp: 1_800.0,
        },
        BuildDef {
            kind: "tunnel_network",
            name: "Tunnel Network",
            faction: "gla",
            cost_gold: 1_100,
            build_ms: 11_000,
            power: 0,
            hp: 2_200.0,
        },
        BuildDef {
            kind: "scud_storm",
            name: "SCUD Storm",
            faction: "gla",
            cost_gold: 7_800,
            build_ms: 48_000,
            power: 0,
            hp: 3_800.0,
        },
        BuildDef {
            kind: "demo_trap",
            name: "Demo Trap",
            faction: "gla",
            cost_gold: 700,
            build_ms: 5_000,
            power: 0,
            hp: 400.0,
        },
    ]
}

pub fn trainables() -> &'static [UnitDef] {
    &[
        // ——— USA infantry ———
        UnitDef {
            unit: "ranger",
            name: "Ranger",
            faction: "usa",
            from_building: "barracks",
            cost_gold: 265,
            train_ms: 5_000,
            hp: 280.0,
            damage: 85.0,
            speed: 0.20,
            range: 4.5,
            attack_ms: 800,
        },
        UnitDef {
            unit: "missile_defender",
            name: "Missile Defender",
            faction: "usa",
            from_building: "barracks",
            cost_gold: 420,
            train_ms: 7_000,
            hp: 260.0,
            damage: 220.0,
            speed: 0.17,
            range: 8.5,
            attack_ms: 2_800,
        },
        UnitDef {
            unit: "pathfinder",
            name: "Pathfinder",
            faction: "usa",
            from_building: "barracks",
            cost_gold: 800,
            train_ms: 12_000,
            hp: 220.0,
            damage: 160.0,
            speed: 0.22,
            range: 9.0,
            attack_ms: 2_200,
        },
        UnitDef {
            unit: "colonel_burton",
            name: "Colonel Burton",
            faction: "usa",
            from_building: "barracks",
            cost_gold: 2_000,
            train_ms: 25_000,
            hp: 900.0,
            damage: 280.0,
            speed: 0.24,
            range: 5.5,
            attack_ms: 900,
        },
        // ——— USA vehicles ———
        UnitDef {
            unit: "humvee",
            name: "Humvee",
            faction: "usa",
            from_building: "war_factory",
            cost_gold: 1_000,
            train_ms: 10_000,
            hp: 1_200.0,
            damage: 95.0,
            speed: 0.72,
            range: 5.5,
            attack_ms: 450,
        },
        UnitDef {
            unit: "tank",
            name: "Crusader Tank",
            faction: "usa",
            from_building: "war_factory",
            cost_gold: 1_600,
            train_ms: 16_000,
            hp: 7_200.0,
            damage: 580.0,
            speed: 0.58,
            range: 8.5,
            attack_ms: 4_800,
        },
        UnitDef {
            unit: "paladin_tank",
            name: "Paladin Tank",
            faction: "usa",
            from_building: "war_factory",
            cost_gold: 2_150,
            train_ms: 22_000,
            hp: 9_500.0,
            damage: 620.0,
            speed: 0.52,
            range: 8.8,
            attack_ms: 5_000,
        },
        UnitDef {
            unit: "tomahawk",
            name: "Tomahawk Launcher",
            faction: "usa",
            from_building: "war_factory",
            cost_gold: 2_400,
            train_ms: 24_000,
            hp: 1_800.0,
            damage: 520.0,
            speed: 0.38,
            range: 8.0,
            attack_ms: 8_500,
        },
        UnitDef {
            unit: "microwave_tank",
            name: "Microwave Tank",
            faction: "usa",
            from_building: "war_factory",
            cost_gold: 1_400,
            train_ms: 18_000,
            hp: 2_400.0,
            damage: 140.0,
            speed: 0.48,
            range: 7.0,
            attack_ms: 1_200,
        },
        UnitDef {
            unit: "mlrs",
            name: "M270 MLRS",
            faction: "usa",
            from_building: "war_factory",
            cost_gold: 3_700,
            train_ms: 42_000,
            hp: 2_200.0,
            damage: 420.0,
            speed: 0.42,
            range: 8.5,
            attack_ms: 9_200,
        },
        // ——— USA air (ground-sim for now; client flies them) ———
        UnitDef {
            unit: "raptor",
            name: "Raptor",
            faction: "usa",
            from_building: "airfield",
            cost_gold: 2_500,
            train_ms: 20_000,
            hp: 1_600.0,
            damage: 380.0,
            speed: 1.15,
            range: 10.0,
            attack_ms: 2_200,
        },
        UnitDef {
            unit: "comanche",
            name: "Comanche",
            faction: "usa",
            from_building: "airfield",
            cost_gold: 2_700,
            train_ms: 22_000,
            hp: 1_400.0,
            damage: 320.0,
            speed: 0.95,
            range: 7.5,
            attack_ms: 900,
        },
        UnitDef {
            unit: "chinook",
            name: "Chinook",
            faction: "usa",
            from_building: "airfield",
            cost_gold: 1_700,
            train_ms: 18_000,
            hp: 2_000.0,
            damage: 40.0,
            speed: 0.70,
            range: 3.0,
            attack_ms: 2_000,
        },
        // ——— China infantry ———
        UnitDef {
            unit: "red_guard",
            name: "Red Guard",
            faction: "china",
            from_building: "barracks",
            cost_gold: 330,
            train_ms: 4_500,
            hp: 300.0,
            damage: 75.0,
            speed: 0.19,
            range: 4.2,
            attack_ms: 850,
        },
        UnitDef {
            unit: "tank_hunter",
            name: "Tank Hunter",
            faction: "china",
            from_building: "barracks",
            cost_gold: 400,
            train_ms: 6_500,
            hp: 250.0,
            damage: 260.0,
            speed: 0.16,
            range: 8.0,
            attack_ms: 3_000,
        },
        UnitDef {
            unit: "hacker",
            name: "Hacker",
            faction: "china",
            from_building: "barracks",
            cost_gold: 675,
            train_ms: 14_000,
            hp: 180.0,
            damage: 20.0,
            speed: 0.15,
            range: 2.0,
            attack_ms: 5_000,
        },
        UnitDef {
            unit: "black_lotus",
            name: "Black Lotus",
            faction: "china",
            from_building: "barracks",
            cost_gold: 1_900,
            train_ms: 28_000,
            hp: 700.0,
            damage: 50.0,
            speed: 0.23,
            range: 6.0,
            attack_ms: 3_500,
        },
        // ——— China vehicles ———
        UnitDef {
            unit: "troop_crawler",
            name: "Troop Crawler",
            faction: "china",
            from_building: "war_factory",
            cost_gold: 1_850,
            train_ms: 16_000,
            hp: 2_800.0,
            damage: 110.0,
            speed: 0.50,
            range: 5.0,
            attack_ms: 600,
        },
        UnitDef {
            unit: "battlemaster",
            name: "Battlemaster Tank",
            faction: "china",
            from_building: "war_factory",
            cost_gold: 1_400,
            train_ms: 14_000,
            hp: 6_500.0,
            damage: 520.0,
            speed: 0.55,
            range: 8.0,
            attack_ms: 4_600,
        },
        UnitDef {
            unit: "gatling_tank",
            name: "Gattling Tank",
            faction: "china",
            from_building: "war_factory",
            cost_gold: 1_450,
            train_ms: 15_000,
            hp: 3_200.0,
            damage: 95.0,
            speed: 0.55,
            range: 7.5,
            attack_ms: 120,
        },
        UnitDef {
            unit: "inferno_cannon",
            name: "Inferno Cannon",
            faction: "china",
            from_building: "war_factory",
            cost_gold: 1_750,
            train_ms: 20_000,
            hp: 2_000.0,
            damage: 480.0,
            speed: 0.36,
            range: 7.0,
            attack_ms: 6_500,
        },
        UnitDef {
            unit: "overlord",
            name: "Overlord Tank",
            faction: "china",
            from_building: "war_factory",
            cost_gold: 3_500,
            train_ms: 35_000,
            hp: 16_000.0,
            damage: 780.0,
            speed: 0.38,
            range: 9.5,
            attack_ms: 5_800,
        },
        UnitDef {
            unit: "listening_outpost",
            name: "Listening Outpost",
            faction: "china",
            from_building: "war_factory",
            cost_gold: 1_150,
            train_ms: 12_000,
            hp: 1_000.0,
            damage: 60.0,
            speed: 0.45,
            range: 5.0,
            attack_ms: 1_000,
        },
        UnitDef {
            unit: "ecm_tank",
            name: "ECM Tank",
            faction: "china",
            from_building: "war_factory",
            cost_gold: 1_300,
            train_ms: 16_000,
            hp: 2_200.0,
            damage: 80.0,
            speed: 0.48,
            range: 8.0,
            attack_ms: 2_000,
        },
        UnitDef {
            unit: "mig",
            name: "MiG",
            faction: "china",
            from_building: "airfield",
            cost_gold: 2_200,
            train_ms: 18_000,
            hp: 1_400.0,
            damage: 400.0,
            speed: 1.20,
            range: 9.5,
            attack_ms: 2_400,
        },
        UnitDef {
            unit: "helix",
            name: "Helix",
            faction: "china",
            from_building: "airfield",
            cost_gold: 2_350,
            train_ms: 22_000,
            hp: 2_200.0,
            damage: 280.0,
            speed: 0.75,
            range: 7.0,
            attack_ms: 1_100,
        },
        // ——— GLA infantry ———
        UnitDef {
            unit: "rebel",
            name: "Rebel",
            faction: "gla",
            from_building: "barracks",
            cost_gold: 170,
            train_ms: 3_500,
            hp: 240.0,
            damage: 70.0,
            speed: 0.21,
            range: 4.0,
            attack_ms: 750,
        },
        UnitDef {
            unit: "rpg_trooper",
            name: "RPG Trooper",
            faction: "gla",
            from_building: "barracks",
            cost_gold: 400,
            train_ms: 6_000,
            hp: 230.0,
            damage: 300.0,
            speed: 0.16,
            range: 7.5,
            attack_ms: 3_200,
        },
        UnitDef {
            unit: "terrorist",
            name: "Terrorist",
            faction: "gla",
            from_building: "barracks",
            cost_gold: 350,
            train_ms: 5_000,
            hp: 200.0,
            damage: 2_500.0,
            speed: 0.25,
            range: 0.8,
            attack_ms: 500,
        },
        UnitDef {
            unit: "hijacker",
            name: "Hijacker",
            faction: "gla",
            from_building: "barracks",
            cost_gold: 450,
            train_ms: 10_000,
            hp: 220.0,
            damage: 40.0,
            speed: 0.22,
            range: 1.2,
            attack_ms: 2_000,
        },
        UnitDef {
            unit: "jarmen_kell",
            name: "Jarmen Kell",
            faction: "gla",
            from_building: "palace",
            cost_gold: 2_000,
            train_ms: 28_000,
            hp: 650.0,
            damage: 450.0,
            speed: 0.20,
            range: 11.0,
            attack_ms: 4_500,
        },
        // ——— GLA vehicles ———
        UnitDef {
            unit: "technical",
            name: "Technical",
            faction: "gla",
            from_building: "arms_dealer",
            cost_gold: 730,
            train_ms: 8_000,
            hp: 900.0,
            damage: 85.0,
            speed: 0.80,
            range: 5.0,
            attack_ms: 400,
        },
        UnitDef {
            unit: "scorpion_tank",
            name: "Scorpion Tank",
            faction: "gla",
            from_building: "arms_dealer",
            cost_gold: 1_050,
            train_ms: 12_000,
            hp: 4_200.0,
            damage: 420.0,
            speed: 0.62,
            range: 7.5,
            attack_ms: 4_200,
        },
        UnitDef {
            unit: "marauder_tank",
            name: "Marauder Tank",
            faction: "gla",
            from_building: "arms_dealer",
            cost_gold: 1_600,
            train_ms: 18_000,
            hp: 7_800.0,
            damage: 640.0,
            speed: 0.48,
            range: 8.2,
            attack_ms: 5_000,
        },
        UnitDef {
            unit: "rocket_buggy",
            name: "Rocket Buggy",
            faction: "gla",
            from_building: "arms_dealer",
            cost_gold: 1_300,
            train_ms: 14_000,
            hp: 1_100.0,
            damage: 280.0,
            speed: 0.88,
            range: 10.0,
            attack_ms: 2_400,
        },
        UnitDef {
            unit: "quad_cannon",
            name: "Quad Cannon",
            faction: "gla",
            from_building: "arms_dealer",
            cost_gold: 1_200,
            train_ms: 13_000,
            hp: 2_000.0,
            damage: 90.0,
            speed: 0.55,
            range: 8.0,
            attack_ms: 150,
        },
        UnitDef {
            unit: "bomb_truck",
            name: "Bomb Truck",
            faction: "gla",
            from_building: "arms_dealer",
            cost_gold: 2_300,
            train_ms: 20_000,
            hp: 1_500.0,
            damage: 4_000.0,
            speed: 0.55,
            range: 1.2,
            attack_ms: 800,
        },
        UnitDef {
            unit: "scud_launcher",
            name: "SCUD Launcher",
            faction: "gla",
            from_building: "arms_dealer",
            cost_gold: 2_500,
            train_ms: 26_000,
            hp: 1_600.0,
            damage: 600.0,
            speed: 0.34,
            range: 7.5,
            attack_ms: 9_000,
        },
        UnitDef {
            unit: "radar_van",
            name: "Radar Van",
            faction: "gla",
            from_building: "arms_dealer",
            cost_gold: 750,
            train_ms: 10_000,
            hp: 900.0,
            damage: 30.0,
            speed: 0.60,
            range: 4.0,
            attack_ms: 2_000,
        },
        UnitDef {
            unit: "battle_bus",
            name: "Battle Bus",
            faction: "gla",
            from_building: "arms_dealer",
            cost_gold: 1_400,
            train_ms: 16_000,
            hp: 3_500.0,
            damage: 100.0,
            speed: 0.52,
            range: 5.5,
            attack_ms: 700,
        },
    ]
}

/// Soft population caps — keep lobbies tank-heavy (tuned for ~8 AI).
pub fn army_cap_for(unit: &str) -> usize {
    match unit {
        "ranger" | "red_guard" | "rebel" => 8,
        "missile_defender" | "tank_hunter" | "rpg_trooper" | "pathfinder" => 5,
        "terrorist" | "hijacker" | "hacker" => 3,
        "colonel_burton" | "black_lotus" | "jarmen_kell" => 1,
        "humvee" | "technical" | "rocket_buggy" => 6,
        "tank" | "battlemaster" | "scorpion_tank" => 10,
        "paladin_tank" | "marauder_tank" => 5,
        "overlord" => 2,
        "gatling_tank" | "quad_cannon" | "microwave_tank" => 5,
        "tomahawk" | "inferno_cannon" | "scud_launcher" | "mlrs" => 3,
        "troop_crawler" | "battle_bus" | "listening_outpost" | "ecm_tank" | "radar_van"
        | "bomb_truck" | "chinook" => 3,
        "raptor" | "mig" | "comanche" | "helix" => 4,
        _ => 6,
    }
}
